{
  "cells": [
    {
      "cell_type": "code",
      "execution_count": null,
      "id": "cafcb57f",
      "metadata": {
        "id": "cafcb57f",
        "outputId": "b53b9c20-0515-4511-dc2d-f7172936fc5b"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Microsoft Windows [Version 10.0.22621.1105]\r\n",
            "(c) Microsoft Corporation. All rights reserved.\r\n",
            "\r\n",
            "C:\\Users\\uday>pip install pandas\n",
            "Requirement already satisfied: pandas in c:\\users\\uday\\anaconda3\\lib\\site-packages (1.4.4)\r\n",
            "Requirement already satisfied: python-dateutil>=2.8.1 in c:\\users\\uday\\anaconda3\\lib\\site-packages (from pandas) (2.8.2)\r\n",
            "Requirement already satisfied: numpy>=1.18.5 in c:\\users\\uday\\anaconda3\\lib\\site-packages (from pandas) (1.23.5)\r\n",
            "Requirement already satisfied: pytz>=2020.1 in c:\\users\\uday\\anaconda3\\lib\\site-packages (from pandas) (2022.7)\r\n",
            "Requirement already satisfied: six>=1.5 in c:\\users\\uday\\anaconda3\\lib\\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)\r\n",
            "\r\n",
            "C:\\Users\\uday>"
          ]
        }
      ],
      "source": [
        "%%cmd\n",
        "pip install pandas"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "id": "723e8388",
      "metadata": {
        "id": "723e8388",
        "outputId": "4df52abd-8a0a-4739-fb82-4910860a670d"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Microsoft Windows [Version 10.0.22621.1105]\r\n",
            "(c) Microsoft Corporation. All rights reserved.\r\n",
            "\r\n",
            "C:\\Users\\uday>pip install face-recognition\n",
            "Collecting face-recognition\r\n",
            "  Using cached face_recognition-1.3.0-py2.py3-none-any.whl (15 kB)\r\n",
            "Requirement already satisfied: Click>=6.0 in c:\\users\\uday\\anaconda3\\lib\\site-packages (from face-recognition) (8.0.4)\r\n",
            "Requirement already satisfied: numpy in c:\\users\\uday\\anaconda3\\lib\\site-packages (from face-recognition) (1.23.5)\r\n",
            "Requirement already satisfied: face-recognition-models>=0.3.0 in c:\\users\\uday\\anaconda3\\lib\\site-packages (from face-recognition) (0.3.0)\r\n",
            "Collecting dlib>=19.7\r\n",
            "  Using cached dlib-19.24.0.tar.gz (3.2 MB)\r\n",
            "  Preparing metadata (setup.py): started\r\n",
            "  Preparing metadata (setup.py): finished with status 'done'\r\n",
            "Requirement already satisfied: Pillow in c:\\users\\uday\\anaconda3\\lib\\site-packages (from face-recognition) (9.3.0)\r\n",
            "Requirement already satisfied: colorama in c:\\users\\uday\\anaconda3\\lib\\site-packages (from Click>=6.0->face-recognition) (0.4.6)\r\n",
            "Building wheels for collected packages: dlib\r\n",
            "  Building wheel for dlib (setup.py): started\r\n",
            "  Building wheel for dlib (setup.py): still running...\r\n",
            "  Building wheel for dlib (setup.py): finished with status 'error'\r\n",
            "  Running setup.py clean for dlib\r\n",
            "Failed to build dlib\r\n",
            "Installing collected packages: dlib, face-recognition\r\n",
            "  Running setup.py install for dlib: started\r\n",
            "  Running setup.py install for dlib: still running...\r\n",
            "  Running setup.py install for dlib: finished with status 'error'\r\n",
            "\r\n",
            "C:\\Users\\uday>"
          ]
        },
        {
          "name": "stderr",
          "output_type": "stream",
          "text": [
            "  error: subprocess-exited-with-error\r\n",
            "  \r\n",
            "  python setup.py bdist_wheel did not run successfully.\r\n",
            "  exit code: 1\r\n",
            "  \r\n",
            "  [306 lines of output]\r\n",
            "  running bdist_wheel\r\n",
            "  running build\r\n",
            "  running build_py\r\n",
            "  running build_ext\r\n",
            "  C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\setup.py:129: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\r\n",
            "    if LooseVersion(cmake_version) < '3.1.0':\r\n",
            "  Building extension for Python 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]\r\n",
            "  Invoking CMake setup: 'cmake C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\lib.win-amd64-cpython-39 -DPYTHON_EXECUTABLE=C:\\Users\\uday\\anaconda3\\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\lib.win-amd64-cpython-39 -A x64'\r\n",
            "  -- Building for: Visual Studio 17 2022\r\n",
            "  -- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.22621.\r\n",
            "  -- The C compiler identification is MSVC 19.34.31942.0\r\n",
            "  -- The CXX compiler identification is MSVC 19.34.31942.0\r\n",
            "  -- Detecting C compiler ABI info\r\n",
            "  -- Detecting C compiler ABI info - done\r\n",
            "  -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe - skipped\r\n",
            "  -- Detecting C compile features\r\n",
            "  -- Detecting C compile features - done\r\n",
            "  -- Detecting CXX compiler ABI info\r\n",
            "  -- Detecting CXX compiler ABI info - done\r\n",
            "  -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe - skipped\r\n",
            "  -- Detecting CXX compile features\r\n",
            "  -- Detecting CXX compile features - done\r\n",
            "  -- Found PythonInterp: C:/Users/uday/anaconda3/python.exe (found version \"3.9.13\")\r\n",
            "  -- Found PythonLibs: C:/Users/uday/anaconda3/libs/Python39.lib\r\n",
            "  -- pybind11 v2.2.4\r\n",
            "  -- Using CMake version: 3.25.2\r\n",
            "  -- Compiling dlib version: 19.24.0\r\n",
            "  -- Looking for sys/types.h\r\n",
            "  -- Looking for sys/types.h - found\r\n",
            "  -- Looking for stdint.h\r\n",
            "  -- Looking for stdint.h - found\r\n",
            "  -- Looking for stddef.h\r\n",
            "  -- Looking for stddef.h - found\r\n",
            "  -- Check size of void*\r\n",
            "  -- Check size of void* - done\r\n",
            "  -- Enabling SSE2 instructions\r\n",
            "  -- Could NOT find WebP (missing: WEBP_LIBRARY)\r\n",
            "  -- Searching for BLAS and LAPACK\r\n",
            "  -- Searching for BLAS and LAPACK\r\n",
            "  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD\r\n",
            "  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed\r\n",
            "  -- Looking for pthread_create in pthreads\r\n",
            "  -- Looking for pthread_create in pthreads - not found\r\n",
            "  -- Looking for pthread_create in pthread\r\n",
            "  -- Looking for pthread_create in pthread - not found\r\n",
            "  -- Found Threads: TRUE\r\n",
            "  CUDA_TOOLKIT_ROOT_DIR not found or specified\r\n",
            "  -- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version \"7.5\")\r\n",
            "  -- Found CUDA, but CMake was unable to find the cuBLAS libraries that should be part of every basic CUDA install. Your CUDA install is somehow broken or incomplete. Since cuBLAS is required for dlib to use CUDA we won't use CUDA.\r\n",
            "  -- DID NOT FIND CUDA\r\n",
            "  -- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA\r\n",
            "  -- C++11 activated.\r\n",
            "  -- Configuring done\r\n",
            "  -- Generating done\r\n",
            "  -- Build files have been written to: C:/Users/uday/AppData/Local/Temp/pip-install-kydevsxe/dlib_9510dfe049b84179a057460efc8619de/build/temp.win-amd64-cpython-39/Release\r\n",
            "  Invoking CMake build: 'cmake --build . --config Release -- /m'\r\n",
            "  MSBuild version 17.4.1+9a89d02ff for .NET Framework\r\n",
            "  C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Microsoft\\VC\\v170\\Microsoft.CppBuild.targets(527,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\ZERO_CHECK.vcxproj]\r\n",
            "    Checking Build System\r\n",
            "  C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Microsoft\\VC\\v170\\Microsoft.CppBuild.targets(527,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\dlib_build\\dlib.vcxproj]\r\n",
            "    Building Custom Rule C:/Users/uday/AppData/Local/Temp/pip-install-kydevsxe/dlib_9510dfe049b84179a057460efc8619de/dlib/CMakeLists.txt\r\n",
            "    base64_kernel_1.cpp\r\n",
            "    bigint_kernel_1.cpp\r\n",
            "    bigint_kernel_2.cpp\r\n",
            "    bit_stream_kernel_1.cpp\r\n",
            "    entropy_decoder_kernel_1.cpp\r\n",
            "    entropy_decoder_kernel_2.cpp\r\n",
            "    entropy_encoder_kernel_1.cpp\r\n",
            "    entropy_encoder_kernel_2.cpp\r\n",
            "    md5_kernel_1.cpp\r\n",
            "    tokenizer_kernel_1.cpp\r\n",
            "    unicode.cpp\r\n",
            "    test_for_odr_violations.cpp\r\n",
            "    sockets_kernel_1.cpp\r\n",
            "    bsp.cpp\r\n",
            "    dir_nav_kernel_1.cpp\r\n",
            "    dir_nav_kernel_2.cpp\r\n",
            "    dir_nav_extensions.cpp\r\n",
            "    fonts.cpp\r\n",
            "    linker_kernel_1.cpp\r\n",
            "    extra_logger_headers.cpp\r\n",
            "    logger_kernel_1.cpp\r\n",
            "    logger_config_file.cpp\r\n",
            "    misc_api_kernel_1.cpp\r\n",
            "    misc_api_kernel_2.cpp\r\n",
            "    sockets_extensions.cpp\r\n",
            "    sockets_kernel_2.cpp\r\n",
            "    sockstreambuf.cpp\r\n",
            "    sockstreambuf_unbuffered.cpp\r\n",
            "    server_kernel.cpp\r\n",
            "    server_iostream.cpp\r\n",
            "    server_http.cpp\r\n",
            "    multithreaded_object_extension.cpp\r\n",
            "    threaded_object_extension.cpp\r\n",
            "    threads_kernel_1.cpp\r\n",
            "    threads_kernel_2.cpp\r\n",
            "    threads_kernel_shared.cpp\r\n",
            "    thread_pool_extension.cpp\r\n",
            "    async.cpp\r\n",
            "    timer.cpp\r\n",
            "    stack_trace.cpp\r\n",
            "    cpu_dlib.cpp\r\n",
            "    tensor_tools.cpp\r\n",
            "    image_dataset_metadata.cpp\r\n",
            "    mnist.cpp\r\n",
            "    cifar.cpp\r\n",
            "    global_function_search.cpp\r\n",
            "    kalman_filter.cpp\r\n",
            "    auto.cpp\r\n",
            "    widgets.cpp\r\n",
            "    drawable.cpp\r\n",
            "    canvas_drawing.cpp\r\n",
            "    style.cpp\r\n",
            "    base_widgets.cpp\r\n",
            "    gui_core_kernel_1.cpp\r\n",
            "    gui_core_kernel_2.cpp\r\n",
            "    png_loader.cpp\r\n",
            "    save_png.cpp\r\n",
            "    jpeg_loader.cpp\r\n",
            "    save_jpeg.cpp\r\n",
            "    arm_init.c\r\n",
            "    filter_neon_intrinsics.c\r\n",
            "    png.c\r\n",
            "    pngerror.c\r\n",
            "    pngget.c\r\n",
            "    pngmem.c\r\n",
            "    pngpread.c\r\n",
            "    pngread.c\r\n",
            "    pngrio.c\r\n",
            "    pngrtran.c\r\n",
            "    pngrutil.c\r\n",
            "    pngset.c\r\n",
            "    pngtrans.c\r\n",
            "    pngwio.c\r\n",
            "    pngwrite.c\r\n",
            "    pngwtran.c\r\n",
            "    pngwutil.c\r\n",
            "    adler32.c\r\n",
            "    compress.c\r\n",
            "    crc32.c\r\n",
            "    deflate.c\r\n",
            "    gzclose.c\r\n",
            "    gzlib.c\r\n",
            "    gzread.c\r\n",
            "    gzwrite.c\r\n",
            "    infback.c\r\n",
            "    inffast.c\r\n",
            "    inflate.c\r\n",
            "  C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\dlib\\external\\zlib\\gzread.c(319,17): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\dlib_build\\dlib.vcxproj]\r\n",
            "  C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\dlib\\external\\zlib\\gzread.c(400,11): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\dlib_build\\dlib.vcxproj]\r\n",
            "  C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\dlib\\external\\zlib\\gzread.c(472,11): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\dlib_build\\dlib.vcxproj]\r\n",
            "  C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\dlib\\external\\zlib\\gzwrite.c(212,24): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\dlib_build\\dlib.vcxproj]\r\n",
            "  C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\dlib\\external\\zlib\\gzwrite.c(232,21): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\dlib_build\\dlib.vcxproj]\r\n",
            "  C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\dlib\\external\\zlib\\gzwrite.c(371,11): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\dlib_build\\dlib.vcxproj]\r\n",
            "    inftrees.c\r\n",
            "    trees.c\r\n",
            "    uncompr.c\r\n",
            "    zutil.c\r\n",
            "    jaricom.c\r\n",
            "    jcapimin.c\r\n",
            "    jcapistd.c\r\n",
            "    jcarith.c\r\n",
            "    jccoefct.c\r\n",
            "    jccolor.c\r\n",
            "    jcdctmgr.c\r\n",
            "    jchuff.c\r\n",
            "    jcinit.c\r\n",
            "    jcmainct.c\r\n",
            "    jcmarker.c\r\n",
            "    jcmaster.c\r\n",
            "    jcomapi.c\r\n",
            "    jcparam.c\r\n",
            "    jcprepct.c\r\n",
            "    jcsample.c\r\n",
            "    jdapimin.c\r\n",
            "    jdapistd.c\r\n",
            "    jdarith.c\r\n",
            "    jdatadst.c\r\n",
            "    jdatasrc.c\r\n",
            "    jdcoefct.c\r\n",
            "    jdcolor.c\r\n",
            "  C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\dlib\\external\\libjpeg\\jdatadst.c(185,34): warning C4267: '=': conversion from 'size_t' to 'unsigned long', possible loss of data [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\dlib_build\\dlib.vcxproj]\r\n",
            "    jddctmgr.c\r\n",
            "    jdhuff.c\r\n",
            "    jdinput.c\r\n",
            "    jdmainct.c\r\n",
            "    jdmarker.c\r\n",
            "    jdmaster.c\r\n",
            "    jdmerge.c\r\n",
            "    jdpostct.c\r\n",
            "    jdsample.c\r\n",
            "    jerror.c\r\n",
            "  C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\dlib\\external\\libjpeg\\jerror.c(193,5): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\dlib_build\\dlib.vcxproj]\r\n",
            "  C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\dlib\\external\\libjpeg\\jerror.c(195,5): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\dlib_build\\dlib.vcxproj]\r\n",
            "    jfdctflt.c\r\n",
            "    jfdctfst.c\r\n",
            "    jfdctint.c\r\n",
            "    jidctflt.c\r\n",
            "    jidctfst.c\r\n",
            "    jidctint.c\r\n",
            "    jmemmgr.c\r\n",
            "    jmemnobs.c\r\n",
            "  C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\dlib\\external\\libjpeg\\jmemmgr.c(307,47): warning C4267: '+=': conversion from 'size_t' to 'long', possible loss of data [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\dlib_build\\dlib.vcxproj]\r\n",
            "  C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\dlib\\external\\libjpeg\\jmemmgr.c(367,46): warning C4267: '+=': conversion from 'size_t' to 'long', possible loss of data [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\dlib_build\\dlib.vcxproj]\r\n",
            "  C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\dlib\\external\\libjpeg\\jmemmgr.c(977,35): warning C4267: '-=': conversion from 'size_t' to 'long', possible loss of data [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\dlib_build\\dlib.vcxproj]\r\n",
            "  C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\dlib\\external\\libjpeg\\jmemmgr.c(991,35): warning C4267: '-=': conversion from 'size_t' to 'long', possible loss of data [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\dlib_build\\dlib.vcxproj]\r\n",
            "  C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\dlib\\external\\libjpeg\\jmemmgr.c(1107,19): warning C4996: 'getenv': This function or variable may be unsafe. Consider using _dupenv_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\dlib_build\\dlib.vcxproj]\r\n",
            "  C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\dlib\\external\\libjpeg\\jmemmgr.c(1110,11): warning C4996: 'sscanf': This function or variable may be unsafe. Consider using sscanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\dlib_build\\dlib.vcxproj]\r\n",
            "    jquant1.c\r\n",
            "    jquant2.c\r\n",
            "    jutils.c\r\n",
            "    dlib.vcxproj -> C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\dlib_build\\Release\\dlib19.24.0_release_64bit_msvc1934.lib\r\n",
            "  C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Microsoft\\VC\\v170\\Microsoft.CppBuild.targets(527,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "    Building Custom Rule C:/Users/uday/AppData/Local/Temp/pip-install-kydevsxe/dlib_9510dfe049b84179a057460efc8619de/tools/python/CMakeLists.txt\r\n",
            "    dlib.cpp\r\n",
            "    matrix.cpp\r\n",
            "    vector.cpp\r\n",
            "    svm_c_trainer.cpp\r\n",
            "    svm_rank_trainer.cpp\r\n",
            "    decision_functions.cpp\r\n",
            "    other.cpp\r\n",
            "    basic.cpp\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\vector.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\dlib.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\other.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\matrix.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\decision_functions.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\svm_c_trainer.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\svm_rank_trainer.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\basic.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "    cca.cpp\r\n",
            "    sequence_segmenter.cpp\r\n",
            "    svm_struct.cpp\r\n",
            "    image.cpp\r\n",
            "    image2.cpp\r\n",
            "    image3.cpp\r\n",
            "    image4.cpp\r\n",
            "    rectangles.cpp\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\cca.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\sequence_segmenter.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\image.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "    object_detection.cpp\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\svm_struct.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\image2.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\image3.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\image4.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "    shape_predictor.cpp\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\rectangles.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "    correlation_tracker.cpp\r\n",
            "    face_recognition.cpp\r\n",
            "    cnn_face_detector.cpp\r\n",
            "    global_optimization.cpp\r\n",
            "    image_dataset_metadata.cpp\r\n",
            "    numpy_returns.cpp\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\object_detection.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\shape_predictor.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\correlation_tracker.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\face_recognition.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\cnn_face_detector.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\image_dataset_metadata.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\global_optimization.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\numpy_returns.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "    line.cpp\r\n",
            "    gui.cpp\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\line.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\gui.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  Traceback (most recent call last):\r\n",
            "    File \"<string>\", line 2, in <module>\r\n",
            "    File \"<pip-setuptools-caller>\", line 34, in <module>\r\n",
            "    File \"C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\setup.py\", line 222, in <module>\r\n",
            "      setup(\r\n",
            "    File \"C:\\Users\\uday\\anaconda3\\lib\\site-packages\\setuptools\\__init__.py\", line 87, in setup\r\n",
            "      return distutils.core.setup(**attrs)\r\n",
            "    File \"C:\\Users\\uday\\anaconda3\\lib\\site-packages\\setuptools\\_distutils\\core.py\", line 185, in setup\r\n",
            "      return run_commands(dist)\r\n",
            "    File \"C:\\Users\\uday\\anaconda3\\lib\\site-packages\\setuptools\\_distutils\\core.py\", line 201, in run_commands\r\n",
            "      dist.run_commands()\r\n",
            "    File \"C:\\Users\\uday\\anaconda3\\lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 969, in run_commands\r\n",
            "      self.run_command(cmd)\r\n",
            "    File \"C:\\Users\\uday\\anaconda3\\lib\\site-packages\\setuptools\\dist.py\", line 1208, in run_command\r\n",
            "      super().run_command(command)\r\n",
            "    File \"C:\\Users\\uday\\anaconda3\\lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 988, in run_command\r\n",
            "      cmd_obj.run()\r\n",
            "    File \"C:\\Users\\uday\\anaconda3\\lib\\site-packages\\wheel\\bdist_wheel.py\", line 325, in run\r\n",
            "      self.run_command(\"build\")\r\n",
            "    File \"C:\\Users\\uday\\anaconda3\\lib\\site-packages\\setuptools\\_distutils\\cmd.py\", line 318, in run_command\r\n",
            "      self.distribution.run_command(command)\r\n",
            "    File \"C:\\Users\\uday\\anaconda3\\lib\\site-packages\\setuptools\\dist.py\", line 1208, in run_command\r\n",
            "      super().run_command(command)\r\n",
            "    File \"C:\\Users\\uday\\anaconda3\\lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 988, in run_command\r\n",
            "      cmd_obj.run()\r\n",
            "    File \"C:\\Users\\uday\\anaconda3\\lib\\site-packages\\setuptools\\_distutils\\command\\build.py\", line 132, in run\r\n",
            "      self.run_command(cmd_name)\r\n",
            "    File \"C:\\Users\\uday\\anaconda3\\lib\\site-packages\\setuptools\\_distutils\\cmd.py\", line 318, in run_command\r\n",
            "      self.distribution.run_command(command)\r\n",
            "    File \"C:\\Users\\uday\\anaconda3\\lib\\site-packages\\setuptools\\dist.py\", line 1208, in run_command\r\n",
            "      super().run_command(command)\r\n",
            "    File \"C:\\Users\\uday\\anaconda3\\lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 988, in run_command\r\n",
            "      cmd_obj.run()\r\n",
            "    File \"C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\setup.py\", line 134, in run\r\n",
            "      self.build_extension(ext)\r\n",
            "    File \"C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\setup.py\", line 174, in build_extension\r\n",
            "      subprocess.check_call(cmake_build, cwd=build_folder)\r\n",
            "    File \"C:\\Users\\uday\\anaconda3\\lib\\subprocess.py\", line 373, in check_call\r\n",
            "      raise CalledProcessError(retcode, cmd)\r\n",
            "  subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '/m']' returned non-zero exit status 1.\r\n",
            "  [end of output]\r\n",
            "  \r\n",
            "  note: This error originates from a subprocess, and is likely not a problem with pip.\r\n",
            "  ERROR: Failed building wheel for dlib\r\n",
            "  error: subprocess-exited-with-error\r\n",
            "  \r\n",
            "  Running setup.py install for dlib did not run successfully.\r\n",
            "  exit code: 1\r\n",
            "  \r\n",
            "  [310 lines of output]\r\n",
            "  running install\r\n",
            "  C:\\Users\\uday\\anaconda3\\lib\\site-packages\\setuptools\\command\\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.\r\n",
            "    warnings.warn(\r\n",
            "  running build\r\n",
            "  running build_py\r\n",
            "  running build_ext\r\n",
            "  C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\setup.py:129: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\r\n",
            "    if LooseVersion(cmake_version) < '3.1.0':\r\n",
            "  Building extension for Python 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]\r\n",
            "  Invoking CMake setup: 'cmake C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\lib.win-amd64-cpython-39 -DPYTHON_EXECUTABLE=C:\\Users\\uday\\anaconda3\\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\lib.win-amd64-cpython-39 -A x64'\r\n",
            "  -- Building for: Visual Studio 17 2022\r\n",
            "  -- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.22621.\r\n",
            "  -- The C compiler identification is MSVC 19.34.31942.0\r\n",
            "  -- The CXX compiler identification is MSVC 19.34.31942.0\r\n",
            "  -- Detecting C compiler ABI info\r\n",
            "  -- Detecting C compiler ABI info - done\r\n",
            "  -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe - skipped\r\n",
            "  -- Detecting C compile features\r\n",
            "  -- Detecting C compile features - done\r\n",
            "  -- Detecting CXX compiler ABI info\r\n",
            "  -- Detecting CXX compiler ABI info - done\r\n",
            "  -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe - skipped\r\n",
            "  -- Detecting CXX compile features\r\n",
            "  -- Detecting CXX compile features - done\r\n",
            "  -- Found PythonInterp: C:/Users/uday/anaconda3/python.exe (found version \"3.9.13\")\r\n",
            "  -- Found PythonLibs: C:/Users/uday/anaconda3/libs/Python39.lib\r\n",
            "  -- pybind11 v2.2.4\r\n",
            "  -- Using CMake version: 3.25.2\r\n",
            "  -- Compiling dlib version: 19.24.0\r\n",
            "  -- Looking for sys/types.h\r\n",
            "  -- Looking for sys/types.h - found\r\n",
            "  -- Looking for stdint.h\r\n",
            "  -- Looking for stdint.h - found\r\n",
            "  -- Looking for stddef.h\r\n",
            "  -- Looking for stddef.h - found\r\n",
            "  -- Check size of void*\r\n",
            "  -- Check size of void* - done\r\n",
            "  -- Enabling SSE2 instructions\r\n",
            "  -- Could NOT find WebP (missing: WEBP_LIBRARY)\r\n",
            "  -- Searching for BLAS and LAPACK\r\n",
            "  -- Searching for BLAS and LAPACK\r\n",
            "  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD\r\n",
            "  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed\r\n",
            "  -- Looking for pthread_create in pthreads\r\n",
            "  -- Looking for pthread_create in pthreads - not found\r\n",
            "  -- Looking for pthread_create in pthread\r\n",
            "  -- Looking for pthread_create in pthread - not found\r\n",
            "  -- Found Threads: TRUE\r\n",
            "  CUDA_TOOLKIT_ROOT_DIR not found or specified\r\n",
            "  -- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version \"7.5\")\r\n",
            "  -- Found CUDA, but CMake was unable to find the cuBLAS libraries that should be part of every basic CUDA install. Your CUDA install is somehow broken or incomplete. Since cuBLAS is required for dlib to use CUDA we won't use CUDA.\r\n",
            "  -- DID NOT FIND CUDA\r\n",
            "  -- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA\r\n",
            "  -- C++11 activated.\r\n",
            "  -- Configuring done\r\n",
            "  -- Generating done\r\n",
            "  -- Build files have been written to: C:/Users/uday/AppData/Local/Temp/pip-install-kydevsxe/dlib_9510dfe049b84179a057460efc8619de/build/temp.win-amd64-cpython-39/Release\r\n",
            "  Invoking CMake build: 'cmake --build . --config Release -- /m'\r\n",
            "  MSBuild version 17.4.1+9a89d02ff for .NET Framework\r\n",
            "  C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Microsoft\\VC\\v170\\Microsoft.CppBuild.targets(527,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\ZERO_CHECK.vcxproj]\r\n",
            "    Checking Build System\r\n",
            "  C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Microsoft\\VC\\v170\\Microsoft.CppBuild.targets(527,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\dlib_build\\dlib.vcxproj]\r\n",
            "    Building Custom Rule C:/Users/uday/AppData/Local/Temp/pip-install-kydevsxe/dlib_9510dfe049b84179a057460efc8619de/dlib/CMakeLists.txt\r\n",
            "    base64_kernel_1.cpp\r\n",
            "    bigint_kernel_1.cpp\r\n",
            "    bigint_kernel_2.cpp\r\n",
            "    bit_stream_kernel_1.cpp\r\n",
            "    entropy_decoder_kernel_1.cpp\r\n",
            "    entropy_decoder_kernel_2.cpp\r\n",
            "    entropy_encoder_kernel_1.cpp\r\n",
            "    entropy_encoder_kernel_2.cpp\r\n",
            "    md5_kernel_1.cpp\r\n",
            "    tokenizer_kernel_1.cpp\r\n",
            "    unicode.cpp\r\n",
            "    test_for_odr_violations.cpp\r\n",
            "    sockets_kernel_1.cpp\r\n",
            "    bsp.cpp\r\n",
            "    dir_nav_kernel_1.cpp\r\n",
            "    dir_nav_kernel_2.cpp\r\n",
            "    fonts.cpp\r\n",
            "    dir_nav_extensions.cpp\r\n",
            "    linker_kernel_1.cpp\r\n",
            "    extra_logger_headers.cpp\r\n",
            "    logger_kernel_1.cpp\r\n",
            "    logger_config_file.cpp\r\n",
            "    misc_api_kernel_1.cpp\r\n",
            "    misc_api_kernel_2.cpp\r\n",
            "    sockets_extensions.cpp\r\n",
            "    sockets_kernel_2.cpp\r\n",
            "    sockstreambuf.cpp\r\n",
            "    sockstreambuf_unbuffered.cpp\r\n",
            "    server_kernel.cpp\r\n",
            "    server_iostream.cpp\r\n",
            "    server_http.cpp\r\n",
            "    multithreaded_object_extension.cpp\r\n",
            "    threaded_object_extension.cpp\r\n",
            "    threads_kernel_1.cpp\r\n",
            "    threads_kernel_2.cpp\r\n",
            "    threads_kernel_shared.cpp\r\n",
            "    thread_pool_extension.cpp\r\n",
            "    async.cpp\r\n",
            "    timer.cpp\r\n",
            "    stack_trace.cpp\r\n",
            "    cpu_dlib.cpp\r\n",
            "    tensor_tools.cpp\r\n",
            "    image_dataset_metadata.cpp\r\n",
            "    mnist.cpp\r\n",
            "    cifar.cpp\r\n",
            "    global_function_search.cpp\r\n",
            "    kalman_filter.cpp\r\n",
            "    auto.cpp\r\n",
            "    widgets.cpp\r\n",
            "    drawable.cpp\r\n",
            "    canvas_drawing.cpp\r\n",
            "    style.cpp\r\n",
            "    base_widgets.cpp\r\n",
            "    gui_core_kernel_1.cpp\r\n",
            "    gui_core_kernel_2.cpp\r\n",
            "    png_loader.cpp\r\n",
            "    save_png.cpp\r\n",
            "    jpeg_loader.cpp\r\n",
            "    save_jpeg.cpp\r\n",
            "    arm_init.c\r\n",
            "    filter_neon_intrinsics.c\r\n",
            "    png.c\r\n",
            "    pngerror.c\r\n",
            "    pngget.c\r\n",
            "    pngmem.c\r\n",
            "    pngpread.c\r\n",
            "    pngread.c\r\n",
            "    pngrio.c\r\n",
            "    pngrtran.c\r\n",
            "    pngrutil.c\r\n",
            "    pngset.c\r\n",
            "    pngtrans.c\r\n",
            "    pngwio.c\r\n",
            "    pngwrite.c\r\n",
            "    pngwtran.c\r\n",
            "    pngwutil.c\r\n",
            "    adler32.c\r\n",
            "    compress.c\r\n",
            "    crc32.c\r\n",
            "    deflate.c\r\n",
            "    gzclose.c\r\n",
            "    gzlib.c\r\n",
            "    gzread.c\r\n",
            "    gzwrite.c\r\n",
            "    infback.c\r\n",
            "    inffast.c\r\n",
            "  C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\dlib\\external\\zlib\\gzwrite.c(212,24): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\dlib_build\\dlib.vcxproj]\r\n",
            "  C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\dlib\\external\\zlib\\gzwrite.c(232,21): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\dlib_build\\dlib.vcxproj]\r\n",
            "  C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\dlib\\external\\zlib\\gzwrite.c(371,11): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\dlib_build\\dlib.vcxproj]\r\n",
            "  C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\dlib\\external\\zlib\\gzread.c(319,17): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\dlib_build\\dlib.vcxproj]\r\n",
            "  C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\dlib\\external\\zlib\\gzread.c(400,11): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\dlib_build\\dlib.vcxproj]\r\n",
            "  C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\dlib\\external\\zlib\\gzread.c(472,11): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\dlib_build\\dlib.vcxproj]\r\n",
            "    inflate.c\r\n",
            "    inftrees.c\r\n",
            "    trees.c\r\n",
            "    uncompr.c\r\n",
            "    zutil.c\r\n",
            "    jaricom.c\r\n",
            "    jcapimin.c\r\n",
            "    jcapistd.c\r\n",
            "    jcarith.c\r\n",
            "    jccoefct.c\r\n",
            "    jccolor.c\r\n",
            "    jcdctmgr.c\r\n",
            "    jchuff.c\r\n",
            "    jcinit.c\r\n",
            "    jcmainct.c\r\n",
            "    jcmarker.c\r\n",
            "    jcmaster.c\r\n",
            "    jcomapi.c\r\n",
            "    jcparam.c\r\n",
            "    jcprepct.c\r\n",
            "    jcsample.c\r\n",
            "    jdapimin.c\r\n",
            "    jdapistd.c\r\n",
            "    jdarith.c\r\n",
            "    jdatadst.c\r\n",
            "    jdatasrc.c\r\n",
            "    jdcoefct.c\r\n",
            "  C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\dlib\\external\\libjpeg\\jdatadst.c(185,34): warning C4267: '=': conversion from 'size_t' to 'unsigned long', possible loss of data [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\dlib_build\\dlib.vcxproj]\r\n",
            "    jdcolor.c\r\n",
            "    jddctmgr.c\r\n",
            "    jdhuff.c\r\n",
            "    jdinput.c\r\n",
            "    jdmainct.c\r\n",
            "    jdmarker.c\r\n",
            "    jdmaster.c\r\n",
            "    jdmerge.c\r\n",
            "    jdpostct.c\r\n",
            "    jdsample.c\r\n",
            "    jerror.c\r\n",
            "    jfdctflt.c\r\n",
            "    jfdctfst.c\r\n",
            "  C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\dlib\\external\\libjpeg\\jerror.c(193,5): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\dlib_build\\dlib.vcxproj]\r\n",
            "  C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\dlib\\external\\libjpeg\\jerror.c(195,5): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\dlib_build\\dlib.vcxproj]\r\n",
            "    jfdctint.c\r\n",
            "    jidctflt.c\r\n",
            "    jidctfst.c\r\n",
            "    jidctint.c\r\n",
            "    jmemmgr.c\r\n",
            "    jmemnobs.c\r\n",
            "    jquant1.c\r\n",
            "  C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\dlib\\external\\libjpeg\\jmemmgr.c(307,47): warning C4267: '+=': conversion from 'size_t' to 'long', possible loss of data [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\dlib_build\\dlib.vcxproj]\r\n",
            "  C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\dlib\\external\\libjpeg\\jmemmgr.c(367,46): warning C4267: '+=': conversion from 'size_t' to 'long', possible loss of data [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\dlib_build\\dlib.vcxproj]\r\n",
            "    jquant2.c\r\n",
            "  C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\dlib\\external\\libjpeg\\jmemmgr.c(977,35): warning C4267: '-=': conversion from 'size_t' to 'long', possible loss of data [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\dlib_build\\dlib.vcxproj]\r\n",
            "  C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\dlib\\external\\libjpeg\\jmemmgr.c(991,35): warning C4267: '-=': conversion from 'size_t' to 'long', possible loss of data [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\dlib_build\\dlib.vcxproj]\r\n",
            "  C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\dlib\\external\\libjpeg\\jmemmgr.c(1107,19): warning C4996: 'getenv': This function or variable may be unsafe. Consider using _dupenv_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\dlib_build\\dlib.vcxproj]\r\n",
            "    jutils.c\r\n",
            "  C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\dlib\\external\\libjpeg\\jmemmgr.c(1110,11): warning C4996: 'sscanf': This function or variable may be unsafe. Consider using sscanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\dlib_build\\dlib.vcxproj]\r\n",
            "    dlib.vcxproj -> C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\dlib_build\\Release\\dlib19.24.0_release_64bit_msvc1934.lib\r\n",
            "  C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Microsoft\\VC\\v170\\Microsoft.CppBuild.targets(527,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "    Building Custom Rule C:/Users/uday/AppData/Local/Temp/pip-install-kydevsxe/dlib_9510dfe049b84179a057460efc8619de/tools/python/CMakeLists.txt\r\n",
            "    dlib.cpp\r\n",
            "    matrix.cpp\r\n",
            "    vector.cpp\r\n",
            "    svm_c_trainer.cpp\r\n",
            "    svm_rank_trainer.cpp\r\n",
            "    decision_functions.cpp\r\n",
            "    other.cpp\r\n",
            "    basic.cpp\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\vector.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\dlib.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\matrix.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\other.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\svm_c_trainer.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\basic.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\decision_functions.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\svm_rank_trainer.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "    cca.cpp\r\n",
            "    sequence_segmenter.cpp\r\n",
            "    svm_struct.cpp\r\n",
            "    image.cpp\r\n",
            "    image2.cpp\r\n",
            "    image3.cpp\r\n",
            "    image4.cpp\r\n",
            "    rectangles.cpp\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\cca.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\sequence_segmenter.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\image.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "    object_detection.cpp\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\svm_struct.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\image2.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\image3.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\image4.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\rectangles.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "    shape_predictor.cpp\r\n",
            "    correlation_tracker.cpp\r\n",
            "    face_recognition.cpp\r\n",
            "    cnn_face_detector.cpp\r\n",
            "    global_optimization.cpp\r\n",
            "    image_dataset_metadata.cpp\r\n",
            "    numpy_returns.cpp\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\object_detection.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\shape_predictor.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\face_recognition.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\correlation_tracker.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\cnn_face_detector.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\global_optimization.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\image_dataset_metadata.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\numpy_returns.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "    line.cpp\r\n",
            "    gui.cpp\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\line.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  C:\\Users\\uday\\anaconda3\\Library\\include\\gif_lib.h(286,61): error C2734: 'GifAsciiTable8x8': 'const' object must be initialized if not 'extern' (compiling source file C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\tools\\python\\src\\gui.cpp) [C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\build\\temp.win-amd64-cpython-39\\Release\\_dlib_pybind11.vcxproj]\r\n",
            "  Traceback (most recent call last):\r\n",
            "    File \"<string>\", line 2, in <module>\r\n",
            "    File \"<pip-setuptools-caller>\", line 34, in <module>\r\n",
            "    File \"C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\setup.py\", line 222, in <module>\r\n",
            "      setup(\r\n",
            "    File \"C:\\Users\\uday\\anaconda3\\lib\\site-packages\\setuptools\\__init__.py\", line 87, in setup\r\n",
            "      return distutils.core.setup(**attrs)\r\n",
            "    File \"C:\\Users\\uday\\anaconda3\\lib\\site-packages\\setuptools\\_distutils\\core.py\", line 185, in setup\r\n",
            "      return run_commands(dist)\r\n",
            "    File \"C:\\Users\\uday\\anaconda3\\lib\\site-packages\\setuptools\\_distutils\\core.py\", line 201, in run_commands\r\n",
            "      dist.run_commands()\r\n",
            "    File \"C:\\Users\\uday\\anaconda3\\lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 969, in run_commands\r\n",
            "      self.run_command(cmd)\r\n",
            "    File \"C:\\Users\\uday\\anaconda3\\lib\\site-packages\\setuptools\\dist.py\", line 1208, in run_command\r\n",
            "      super().run_command(command)\r\n",
            "    File \"C:\\Users\\uday\\anaconda3\\lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 988, in run_command\r\n",
            "      cmd_obj.run()\r\n",
            "    File \"C:\\Users\\uday\\anaconda3\\lib\\site-packages\\setuptools\\command\\install.py\", line 68, in run\r\n",
            "      return orig.install.run(self)\r\n",
            "    File \"C:\\Users\\uday\\anaconda3\\lib\\site-packages\\setuptools\\_distutils\\command\\install.py\", line 698, in run\r\n",
            "      self.run_command('build')\r\n",
            "    File \"C:\\Users\\uday\\anaconda3\\lib\\site-packages\\setuptools\\_distutils\\cmd.py\", line 318, in run_command\r\n",
            "      self.distribution.run_command(command)\r\n",
            "    File \"C:\\Users\\uday\\anaconda3\\lib\\site-packages\\setuptools\\dist.py\", line 1208, in run_command\r\n",
            "      super().run_command(command)\r\n",
            "    File \"C:\\Users\\uday\\anaconda3\\lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 988, in run_command\r\n",
            "      cmd_obj.run()\r\n",
            "    File \"C:\\Users\\uday\\anaconda3\\lib\\site-packages\\setuptools\\_distutils\\command\\build.py\", line 132, in run\r\n",
            "      self.run_command(cmd_name)\r\n",
            "    File \"C:\\Users\\uday\\anaconda3\\lib\\site-packages\\setuptools\\_distutils\\cmd.py\", line 318, in run_command\r\n",
            "      self.distribution.run_command(command)\r\n",
            "    File \"C:\\Users\\uday\\anaconda3\\lib\\site-packages\\setuptools\\dist.py\", line 1208, in run_command\r\n",
            "      super().run_command(command)\r\n",
            "    File \"C:\\Users\\uday\\anaconda3\\lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 988, in run_command\r\n",
            "      cmd_obj.run()\r\n",
            "    File \"C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\setup.py\", line 134, in run\r\n",
            "      self.build_extension(ext)\r\n",
            "    File \"C:\\Users\\uday\\AppData\\Local\\Temp\\pip-install-kydevsxe\\dlib_9510dfe049b84179a057460efc8619de\\setup.py\", line 174, in build_extension\r\n",
            "      subprocess.check_call(cmake_build, cwd=build_folder)\r\n",
            "    File \"C:\\Users\\uday\\anaconda3\\lib\\subprocess.py\", line 373, in check_call\r\n",
            "      raise CalledProcessError(retcode, cmd)\r\n",
            "  subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '/m']' returned non-zero exit status 1.\r\n",
            "  [end of output]\r\n",
            "  \r\n",
            "  note: This error originates from a subprocess, and is likely not a problem with pip.\r\n",
            "error: legacy-install-failure\r\n",
            "\r\n",
            "Encountered error while trying to install package.\r\n",
            "\r\n",
            "dlib\r\n",
            "\r\n",
            "note: This is an issue with the package mentioned above, not pip.\r\n",
            "hint: See above for output from the failure.\r\n"
          ]
        }
      ],
      "source": [
        "%%cmd\n",
        "pip install face-recognition"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "id": "3814e5f3",
      "metadata": {
        "id": "3814e5f3",
        "outputId": "0deba8a3-048a-4c1c-abae-33be10d9c421"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Microsoft Windows [Version 10.0.22621.1105]\r\n",
            "(c) Microsoft Corporation. All rights reserved.\r\n",
            "\r\n",
            "C:\\Users\\uday>pip install cmake\n",
            "Requirement already satisfied: cmake in c:\\users\\uday\\anaconda3\\lib\\site-packages (3.25.2)\r\n",
            "\r\n",
            "C:\\Users\\uday>"
          ]
        }
      ],
      "source": [
        "%%cmd\n",
        "pip install cmake"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "id": "2a7980d6",
      "metadata": {
        "scrolled": true,
        "id": "2a7980d6",
        "outputId": "de77691c-f410-462f-a62c-2b4ab3630c3c"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Microsoft Windows [Version 10.0.22621.1105]\r\n",
            "(c) Microsoft Corporation. All rights reserved.\r\n",
            "\r\n",
            "C:\\Users\\uday>pip install \"C:\\Users\\uday\\Downloads\\Install-dlib-main\\Install-dlib-main\\dlib-19.22.99-cp39-cp39-win_amd64.whl\"\n",
            "Processing c:\\users\\uday\\downloads\\install-dlib-main\\install-dlib-main\\dlib-19.22.99-cp39-cp39-win_amd64.whl\r\n",
            "Installing collected packages: dlib\r\n",
            "Successfully installed dlib-19.22.99\r\n",
            "\r\n",
            "C:\\Users\\uday>"
          ]
        }
      ],
      "source": [
        "%%cmd\n",
        "pip install \"C:\\Users\\uday\\Downloads\\Install-dlib-main\\Install-dlib-main\\dlib-19.22.99-cp39-cp39-win_amd64.whl\""
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "id": "10f03809",
      "metadata": {
        "id": "10f03809",
        "outputId": "358cbf1d-a3f1-4aae-d86b-95cf2792b896"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Microsoft Windows [Version 10.0.22621.1105]\r\n",
            "(c) Microsoft Corporation. All rights reserved.\r\n",
            "\r\n",
            "C:\\Users\\uday>pip install face-recognition\n",
            "Collecting face-recognition\r\n",
            "  Using cached face_recognition-1.3.0-py2.py3-none-any.whl (15 kB)\r\n",
            "Requirement already satisfied: numpy in c:\\users\\uday\\anaconda3\\lib\\site-packages (from face-recognition) (1.23.5)\r\n",
            "Requirement already satisfied: Pillow in c:\\users\\uday\\anaconda3\\lib\\site-packages (from face-recognition) (9.3.0)\r\n",
            "Requirement already satisfied: face-recognition-models>=0.3.0 in c:\\users\\uday\\anaconda3\\lib\\site-packages (from face-recognition) (0.3.0)\r\n",
            "Requirement already satisfied: dlib>=19.7 in c:\\users\\uday\\anaconda3\\lib\\site-packages (from face-recognition) (19.22.99)\r\n",
            "Requirement already satisfied: Click>=6.0 in c:\\users\\uday\\anaconda3\\lib\\site-packages (from face-recognition) (8.0.4)\r\n",
            "Requirement already satisfied: colorama in c:\\users\\uday\\anaconda3\\lib\\site-packages (from Click>=6.0->face-recognition) (0.4.6)\r\n",
            "Installing collected packages: face-recognition\r\n",
            "Successfully installed face-recognition-1.3.0\r\n",
            "\r\n",
            "C:\\Users\\uday>"
          ]
        }
      ],
      "source": [
        "%%cmd\n",
        "pip install face-recognition"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "id": "4c6653e8",
      "metadata": {
        "id": "4c6653e8"
      },
      "outputs": [],
      "source": [
        "import face_recognition as fr"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "id": "0d157aba",
      "metadata": {
        "id": "0d157aba"
      },
      "outputs": [],
      "source": [
        "from PIL import Image,ImageDraw"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "id": "ca00b345",
      "metadata": {
        "id": "ca00b345"
      },
      "outputs": [],
      "source": [
        "virat_image=fr.load_image_file(r\"C:\\Users\\uday\\Downloads\\ssvv.png\")\n",
        "virat_encoding=fr.face_encodings (virat_image)[0]"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "id": "0cc7abb5",
      "metadata": {
        "id": "0cc7abb5"
      },
      "outputs": [],
      "source": [
        "known_encodings=[virat_encoding]\n",
        "known_names=[\"virat\"]"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "id": "77d9be71",
      "metadata": {
        "id": "77d9be71"
      },
      "outputs": [],
      "source": [
        "test_image=fr.load_image_file(r\"C:\\Users\\uday\\Downloads\\vigro.jpg\")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "id": "20892ce3",
      "metadata": {
        "id": "20892ce3"
      },
      "outputs": [],
      "source": [
        "face_locations=fr.face_locations(test_image)\n",
        "face_encodings=fr.face_encodings(test_image,face_locations)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "id": "612a5cbb",
      "metadata": {
        "id": "612a5cbb",
        "outputId": "ccbf9ef1-7fc7-4752-9e72-2bdee09a284b"
      },
      "outputs": [
        {
          "name": "stderr",
          "output_type": "stream",
          "text": [
            "C:\\Users\\uday\\AppData\\Local\\Temp\\ipykernel_28364\\2820752572.py:12: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.\n",
            "  text_width, text_height=draw.textsize (name)\n"
          ]
        }
      ],
      "source": [
        "pil_image=Image.fromarray(test_image)\n",
        "draw=ImageDraw.Draw(pil_image)\n",
        "for (top, right, bottom, left), face_encoding in zip(face_locations, face_encodings):\n",
        "    matches=fr.compare_faces(known_encodings, face_encoding,0.4)\n",
        "\n",
        "    name=\"Unknown\"\n",
        "\n",
        "    if True in matches:\n",
        "        first_match_index=matches.index (True)\n",
        "        name=known_names[first_match_index]\n",
        "        draw.rectangle(((left,top),(right,bottom)),outline=(0,0,0))\n",
        "        text_width, text_height=draw.textsize (name)\n",
        "        draw.rectangle(((left, bottom-text_height-10), (right, bottom)),outline=(0,0,0))\n",
        "        draw.text ((left+6, bottom-text_height-5), name, fill=(255,255,255,255))\n",
        "        \n",
        "\n",
        "pil_image.show()\n",
        "\n",
        "pil_image.save(\"output.jpeg\")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "id": "d13368e5",
      "metadata": {
        "id": "d13368e5"
      },
      "outputs": [],
      "source": [
        "import face_recognition\n",
        "from PIL import Image, ImageDraw\n",
        "\n",
        "# Load the single photo and the group photo\n",
        "single_photo = face_recognition.load_image_file(r\"C:\\Users\\uday\\Downloads\\ssvv.png\")\n",
        "group_photo = face_recognition.load_image_file(r\"C:\\Users\\uday\\Downloads\\vigro.jpg\")\n",
        "\n",
        "# Compute the face encodings for both photos\n",
        "single_photo_encodings = face_recognition.face_encodings(single_photo)\n",
        "group_photo_encodings = face_recognition.face_encodings(group_photo)\n",
        "\n",
        "# Compare the face encodings to find the most similar match\n",
        "best_match_index = -1\n",
        "best_match_distance = 1.0  # initialize with maximum possible distance\n",
        "\n",
        "for i in range(len(group_photo_encodings)):\n",
        "    distance = face_recognition.face_distance([single_photo_encodings[0]], group_photo_encodings[i])[0]\n",
        "    if distance < best_match_distance:\n",
        "        best_match_distance = distance\n",
        "        best_match_index = i\n",
        "\n",
        "# Extract and save the best match face from the group photo\n",
        "if best_match_index != -1:\n",
        "    (top, right, bottom, left) = face_recognition.face_locations(group_photo)[best_match_index]\n",
        "    best_match_face = group_photo[top:bottom, left:right]\n",
        "    \n",
        "    # Save the cropped face as a separate image file\n",
        "    cropped_image = Image.fromarray(best_match_face)\n",
        "    cropped_image.save(\"detected_face.jpg\")\n",
        "    \n",
        "    # Draw a rectangle around the detected face in the group photo\n",
        "    draw = ImageDraw.Draw(Image.fromarray(group_photo))\n",
        "    draw.rectangle(((left, top), (right, bottom)), outline=(0, 0, 255), width=2)\n",
        "    \n",
        "    # Save the marked-up group photo as a separate image file\n",
        "    Image.fromarray(group_photo).save(\"group_photo_marked.jpg\")\n",
        "    \n",
        "    # Show the detected face image and the marked-up group photo\n",
        "    cropped_image.show()\n",
        "    Image.fromarray(group_photo).show()\n",
        "else:\n",
        "    print(\"No matching face found in group photo\")\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "id": "7a97ecdb",
      "metadata": {
        "id": "7a97ecdb",
        "outputId": "0413b45a-c369-46f0-a226-4cffd53fa571"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "correct face ID\n"
          ]
        }
      ],
      "source": [
        "import face_recognition\n",
        "\n",
        "# Load the cropped face and the original single photo\n",
        "cropped_face = face_recognition.load_image_file(\"group_photo_marked.jpg\")\n",
        "single_photo = face_recognition.load_image_file(r\"C:\\Users\\uday\\Downloads\\ssvv.png\")\n",
        "\n",
        "# Compute the face encodings for both photos\n",
        "cropped_face_encodings = face_recognition.face_encodings(cropped_face)\n",
        "single_photo_encodings = face_recognition.face_encodings(single_photo)\n",
        "\n",
        "# Compare the face encodings to find the similarity percentage\n",
        "face_distances = face_recognition.face_distance(single_photo_encodings, cropped_face_encodings[0])\n",
        "similarity_percentage = 100 - (face_distances[0] * 100)\n",
        "\n",
        "# Print the similarity percentage\n",
        "#print(\"The similarity percentage between the single photo face and the cropped face is: \", similarity_percentage, \"%\")\n",
        "\n",
        "\n",
        "if similarity_percentage>40:\n",
        "    print(\"correct face ID\")\n",
        "else:\n",
        "    print(\"Incorrect face ID\")"
      ]
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3 (ipykernel)",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.9.13"
    },
    "colab": {
      "provenance": []
    }
  },
  "nbformat": 4,
  "nbformat_minor": 5
}